name: CI

on:
  pull_request:
    branches: [ main ]

# https://github.com/pnpm/action-setup
jobs:
  define-matrix:
    runs-on: ubuntu-22.04

    outputs:
      node: ${{ steps.define-matrix.outputs.node-version }}

    steps:
      - name: Define Node version
        id: node-version
        run: cat .node-version | xargs -I {value} echo "NODE_VERSION={value}" >> $GITHUB_ENV

  ci:
    runs-on: ubuntu-22.04
    needs: define-matrix
    strategy:
      matrix:
        node-version: ${{ needs.define-matrix.outputs.node-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        # Omit version input to use the version in the packageManager field in the package.json.
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run eslint
        run: pnpm lint

      - name: Run type check
        run: pnpm type-check

      - name: Run validate dependency
        run: pnpm validate:dependency
